### ISSUE TITLE
ppx: response to other query while reusing connections

### ISSUE THREAD

**Issue by NightBlues** [darioteixeira/pgocaml#98]
I'm using Lwt_pool to reuse connections like this:
```
  Lwt_pool.create pool_size
    ~validate:PGOCaml.alive
    ~dispose:PGOCaml.close
    (PGOCaml.connect ~host ~port ~user ~password ~database))
```
and caught strange bug - getting results for different query. I'm not sure why it happens - may be some lwt threads are getting canceled. The error can be clearly seen because of cool error that ppx generates here: https://github.com/darioteixeira/pgocaml/blob/master/ppx/ppx_pgsql.ml#L561
I see that ppx generates unique name for prepared statement: https://github.com/darioteixeira/pgocaml/blob/master/ppx/ppx_pgsql.ml#L493 but not for portals.
I think (but I'm not sure) that explicit naming of portals instead of using default name "" could solve the bug.
I could try to create a PR if my thoughts are correct.

**Comment by vouillon** [comment]
You need to make sure that you are not catching any of the exceptions `PGOCaml.Error _`, `Lwt.Canceled` while using a connection, and add the argument `~check:(fun _ f -> f false)` to `Lwt_pool.create` so that `Lwt_pool.use` disposes of the connection.
Alternatively, you can explicitly close the connection when one of these exceptions are raised (and the validation function will take care of removing the connection from the pool):
```ocaml
let use_pool f =
  Lwt_pool.use pool @@ fun db ->
  try%lwt
    f db
  with (Lwt_PGOCaml.Error _ | | Lwt.Canceled) as e ->
    let%lwt () = Lwt_PGOCaml.close db in Lwt.fail e
```
You should also check that use are not using the same connection simultaneously for two requests.
```ocaml
Lwt_pool.use pool @@ fun db ->
let r1 = [%pgsql db "SELECT ..."] in
let r2 = [%pgsql db "SELECT ..."] in
...
```

**Comment by NightBlues** [comment]
> You should also check that use are not using the same connection simultaneously for two requests.

This was the first trouble I've found with Lwt_list.map_p :) 

> add the argument ~check:(fun _ f -> f false) to Lwt_pool.create so that Lwt_pool.use disposes of the connection.

Thats's a good point! But what do you think about named portals - will it work? :)

**Comment by vouillon** [comment]
Named portals will not work since you have no guarantee that statements are executed atomically.
